# Generated by Django 5.2.5 on 2025-11-19 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenazaMarina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AreaProtegida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('regulacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contaminante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('peligrosidad', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieMarina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=255)),
                ('nombreComun', models.CharField(blank=True, max_length=255)),
                ('estadoUICN', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('fechaFuente', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaAlta', models.DateField()),
                ('idioma', models.CharField(blank=True, max_length=50)),
                ('privacidadRanking', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('umbralXP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sitioWeb', models.URLField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('licencia', models.CharField(blank=True, max_length=100)),
                ('fuente', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.especiemarina')),
            ],
        ),
        migrations.CreateModel(
            name='EspecieAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAmenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.amenazamarina')),
                ('idEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.especiemarina')),
            ],
            options={
                'unique_together': {('idEspecie', 'idAmenaza')},
            },
        ),
        migrations.AddField(
            model_name='amenazamarina',
            name='especies',
            field=models.ManyToManyField(related_name='amenazas', through='marina.EspecieAmenaza', to='marina.especiemarina'),
        ),
        migrations.CreateModel(
            name='HabitatMarino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('especies', models.ManyToManyField(related_name='habitats', through='marina.EspecieHabitat', to='marina.especiemarina')),
            ],
        ),
        migrations.AddField(
            model_name='especiehabitat',
            name='idHabitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.habitatmarino'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('skin', models.CharField(blank=True, max_length=100)),
                ('accesorios', models.TextField(blank=True)),
                ('ultimaEdicion', models.DateTimeField(auto_now=True)),
                ('idJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='marina.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('idJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('dificultad', models.IntegerField(default=1)),
                ('puntos', models.IntegerField(default=0)),
                ('objetivosJSON', models.JSONField(blank=True, null=True)),
                ('idHabitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marina.habitatmarino')),
                ('jugadores', models.ManyToManyField(related_name='misiones', through='marina.JugadorMision', to='marina.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugadormision',
            name='idMision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.mision'),
        ),
        migrations.CreateModel(
            name='MisionContaminante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContaminante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.contaminante')),
                ('idMision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.mision')),
            ],
            options={
                'unique_together': {('idMision', 'idContaminante')},
            },
        ),
        migrations.AddField(
            model_name='mision',
            name='contaminantes',
            field=models.ManyToManyField(blank=True, through='marina.MisionContaminante', to='marina.contaminante'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='idNivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marina.niveljuego'),
        ),
        migrations.CreateModel(
            name='ObjetoRecolectable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valorPuntos', models.IntegerField(default=0)),
                ('idContaminante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marina.contaminante')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('sitioWeb', models.URLField(blank=True)),
                ('idArea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marina.areaprotegida')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMarino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.proyectoconservacion')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.organizacion')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.proyectoconservacion')),
            ],
            options={
                'unique_together': {('idProyecto', 'idOrg')},
            },
        ),
        migrations.AddField(
            model_name='proyectoconservacion',
            name='organizaciones',
            field=models.ManyToManyField(blank=True, through='marina.ProyectoOrganizacion', to='marina.organizacion'),
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('idJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='MisionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.mision')),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina.recursoeducativo')),
            ],
            options={
                'unique_together': {('idMision', 'idRecurso')},
            },
        ),
        migrations.AddField(
            model_name='mision',
            name='recursos',
            field=models.ManyToManyField(blank=True, through='marina.MisionRecurso', to='marina.recursoeducativo'),
        ),
        migrations.AlterUniqueTogether(
            name='especiehabitat',
            unique_together={('idEspecie', 'idHabitat')},
        ),
        migrations.AlterUniqueTogether(
            name='jugadormision',
            unique_together={('idJugador', 'idMision')},
        ),
    ]
