# Generated by Django 5.2.5 on 2025-11-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='idNivel',
        ),
        migrations.DeleteModel(
            name='NivelJuego',
        ),
    ]
