# Generated by Django 5.2.5 on 2025-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina', '0002_remove_jugador_idnivel_delete_niveljuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='privacidadRanking',
            field=models.BooleanField(default=False),
        ),
    ]
